### ISSUE TITLE
Suggestion: Option to record HTTP Header data without downloading

### ISSUE THREAD

**Issue by mariomadproductions** [luigoalma/ctrcdnfetch#1]
I want to record this data, but I can't do so for titles that are restricted because I can't use wget for those. Could you add support for recording HTTP header data, specifying specific CDN files or tell me how I can use genuine tickets to download with wget?

**Comment by luigoalma** [comment]
To see if I understood, you want it to print headers used?
They are base64 encoded and encrypted, the data result is always different because it uses randomly generated keys on tickets

**Comment by mariomadproductions** [comment]
Sorry, I meant the response headers. I'd like to record the response headers for restricted titles.

**Comment by luigoalma** [comment]
< HTTP/1.1 200 OK\
< Last-Modified: Mon, 16 Nov 2015 13:36:49 GMT\
< Content-Length: 2994176\
< Content-Type: application/octet-stream\
< Cache-Control: public, max-age=600\
< Expires: Sun, 07 Oct 2018 18:30:37 GMT\
< Date: Sun, 07 Oct 2018 18:20:37 GMT\
< Connection: keep-alive

you mean like these? its all that gets reported back by libcurl in verbose

**Comment by mariomadproductions** [comment]
yeah that's what I'm looking for. I can do it for unrestricted titles by using wget, but not with restricted titles.

**Comment by luigoalma** [comment]
i can make them print yea
only want response headers? of all content entries i assume

**Comment by luigoalma** [comment]
also what purpose exactly?
if for content sizes we might as well just read TMD for them

**Comment by mariomadproductions** [comment]
Thanks. I'm interested in the Last-Modified dates.

**Comment by luigoalma** [comment]
I'll address this once i'm doing with making other code, I'm in the progress of clearing main.cpp, since i'll have to change main.cpp for this, i'll get to it once stuff is done

**Comment by mariomadproductions** [comment]
Thanks

**Comment by luigoalma** [comment]
Does referenced commit (957d4d6) do what you need?
If you need a build, ping.

**Comment by luigoalma** [comment]
I'll assume so, closing this until said otherwise

**Comment by mariomadproductions** [comment]
It looks like it, thanks. Could you make a build?

**Comment by luigoalma** [comment]
Heres this, won't call it a release, i'll consider for testing
[ctrcdnfetch.zip](https://github.com/luigoalma/ctrcdnfetch/files/2522844/ctrcdnfetch.zip)
-r for response headers, -n for them too if you don't want to download the title

**Comment by mariomadproductions** [comment]
Thanks, I'll hopefully try this out soon.
